parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    MainBundle\:
        resource: '../../src/MainBundle/*'
        exclude: '../../src/MainBundle/{Entity,Repository}'
