parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    MainBundle\:
        resource: '../../src/MainBundle/*'
        exclude: '../../src/MainBundle/{Entity,Repository}'
    login_listener:
        class:  MainBundle\Listeners\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }