parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    MainBundle\:
        resource: '../../src/MainBundle/*'
        exclude: '../../src/MainBundle/{Entity,Repository}'
    login_listener:
        class:  MainBundle\Listeners\LoginListener
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    app.menu_builder:
        class: MainBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: mainMenu }