<?php

namespace MainBundle\Repository;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
