<?php

namespace MainBundle\Repository;

/**
 * OptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
