<?php

namespace MainBundle\Repository;

/**
 * PublicBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicBookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
