<?php

namespace MainBundle\Repository;

/**
 * UserConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConnectionRepository extends \Doctrine\ORM\EntityRepository
{
}
